trigger:
- Backend007

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerRegistry: 'indiarg1.azurecr.io'
  dockerRegistryServiceConnection: 'azure-registry'
  imageRepository: 'test'
  tag: '$(Build.BuildId)'
  dockerfilePath: 'Dockerfile'

steps:

# Build Maven App
- task: Maven@4
  displayName: "Maven Build"
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install -DskipTests=true'

# Build Docker Image
- task: Docker@2
  displayName: "Build Docker Image"
  inputs:
    command: build
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    tags: |
      $(tag)

# Push Image to ACR
- task: Docker@2
  displayName: "Push Docker Image to ACR"
  inputs:
    command: push
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    tags: |
      $(tag)
