trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'maheshendcontainer'
  imageName: 'test'
  registryName: 'maheshendcontainer.azurecr.io'
  tag: '$(Build.BuildId)'

steps:
# Login to ACR
- task: Docker@2
  displayName: "Login to ACR"
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)

# Build Docker image
- task: Docker@2
  displayName: "Build Docker Image"
  inputs:
    command: build
    repository: $(registryName)/$(imageName)
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)

# Push Docker image to ACR
- task: Docker@2
  displayName: "Push Docker Image to ACR"
  inputs:
    command: push
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(registryName)/$(imageName)
    tags: |
      $(tag)
